def testing_pods
  pod 'RxSwift'
  pod 'RxBlocking'
  pod 'RxTest'
end

use_frameworks!

target 'TypicodePhotoCollection' do
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
  pod 'Kingfisher', '~> 5.15'
  pod 'SwiftLint'
  pod 'lottie-ios'
  
  target 'TypicodePhotoCollectionTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end
  
end
